# Posttest 7 : TensorFlow
# Nama : Adlina Safa Sephia Putri
# NIM : 2109106021

## Ketentuan :
1. Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.
2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.
3. Tampilkan dimensi dari kedua variable tersebut.
4. Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).
5. Tampilkan nilai maksimum dan minimum dari variable random_tensor.
6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)
7. Tampilkan hasil sorting dari kedua variable di atas (descending)

In [2]:
import tensorflow as tf

### 1. Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [3]:
random_tensor = tf.random.normal([5,5])
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.80157036, -0.76805395,  0.04750545,  0.60564154,  0.11260842],
       [ 0.53367996,  1.586856  , -0.59431523, -0.96461004,  0.43951255],
       [-0.7236123 ,  0.42185962, -2.035601  , -0.5865435 , -0.34588125],
       [ 0.79031557,  0.21720563,  1.6272932 , -1.4197527 ,  1.8100669 ],
       [ 0.09864461,  2.090741  , -0.05208602, -0.43903086,  0.19157891]],
      dtype=float32)>

### 2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [4]:
prime_tensor = tf.constant([2, 3, 5, 7, 11,
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47,
                            53, 59, 61, 67, 71,
                            73, 79, 83, 89, 97], shape=[5, 5], dtype=tf.float32)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)>

### 3. Tampilkan dimensi dari kedua variable tersebut.

#### Dimensi Display Random_Tensor

In [5]:
dim_display_random = tf.constant(['random_tensor'], shape=[5,5])
dim_display_random.shape

TensorShape([5, 5])

In [6]:
tf.shape(dim_display_random)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

#### Dimensi Display Prime_Tensor

In [7]:
dim_display_prime = tf.constant(['prime_tensor'], shape=[5,5])
dim_display_prime.shape

TensorShape([5, 5])

In [8]:
tf.shape(dim_display_prime)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

### 4. Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

#### Operator Penjumlahan

In [9]:
print("==============================================================")
print("Hasil Penjumlahan dari Variable RANDOM_TENSOR dan PRIME_TENSOR")
print("==============================================================")
tf.add(random_tensor, prime_tensor)

Hasil Penjumlahan dari Variable RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.8015704,  2.231946 ,  5.0475054,  7.6056414, 11.112608 ],
       [13.53368  , 18.586857 , 18.405685 , 22.03539  , 29.439512 ],
       [30.276388 , 37.42186  , 38.964397 , 42.413456 , 46.654118 ],
       [53.790314 , 59.217205 , 62.627293 , 65.580246 , 72.81007  ],
       [73.09865  , 81.090744 , 82.947914 , 88.56097  , 97.19158  ]],
      dtype=float32)>

#### Operator Pengurangan

In [10]:
print("==============================================================")
print("Hasil Pengurangan dari Variable RANDOM_TENSOR dan PRIME_TENSOR")
print("==============================================================")
tf.subtract(random_tensor, prime_tensor)

Hasil Pengurangan dari Variable RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.1984296,  -3.768054 ,  -4.9524946,  -6.3943586, -10.887392 ],
       [-12.46632  , -15.413144 , -19.594315 , -23.96461  , -28.560488 ],
       [-31.723612 , -36.57814  , -43.035603 , -43.586544 , -47.345882 ],
       [-52.209686 , -58.782795 , -59.372707 , -68.419754 , -69.18993  ],
       [-72.90135  , -76.909256 , -83.052086 , -89.43903  , -96.80842  ]],
      dtype=float32)>

#### Operator Perkalian

In [11]:
print("==============================================================")
print("Hasil Perkalian dari Variable RANDOM_TENSOR dan PRIME_TENSOR")
print("==============================================================")
tf.multiply(random_tensor, prime_tensor)

Hasil Perkalian dari Variable RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.6031407 ,  -2.3041618 ,   0.23752727,   4.239491  ,
          1.2386926 ],
       [  6.9378395 ,  26.976553  , -11.291989  , -22.186031  ,
         12.745864  ],
       [-22.431982  ,  15.608806  , -83.45964   , -25.22137   ,
        -16.256418  ],
       [ 41.886726  ,  12.815132  ,  99.264885  , -95.12343   ,
        128.51476   ],
       [  7.201057  , 165.16853   ,  -4.3231397 , -39.073746  ,
         18.583155  ]], dtype=float32)>

#### Operator Pembagian

In [12]:
print("==============================================================")
print("Hasil Pembagian dari Variable RANDOM_TENSOR dan PRIME_TENSOR")
print("==============================================================")
tf.divide(random_tensor, prime_tensor)

Hasil Pembagian dari Variable RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.40078518, -0.25601798,  0.00950109,  0.08652022,  0.01023713],
       [ 0.0410523 ,  0.09334447, -0.03127975, -0.04193957,  0.01515561],
       [-0.02334233,  0.01140161, -0.0496488 , -0.01364055, -0.00735918],
       [ 0.01491161,  0.00368145,  0.02667694, -0.02119034,  0.0254939 ],
       [ 0.0013513 ,  0.02646508, -0.00062754, -0.00493293,  0.00197504]],
      dtype=float32)>

#### Operator Pangkat

In [13]:
print("==============================================================")
print("Hasil Pangkat dari Variable RANDOM_TENSOR dan PRIME_TENSOR")
print("==============================================================")
tf.pow(random_tensor, prime_tensor)

Hasil Pangkat dari Variable RANDOM_TENSOR dan PRIME_TENSOR


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 6.42515063e-01, -4.53080297e-01,  2.41945372e-07,
         2.98888776e-02,  3.69215075e-11],
       [ 2.84873240e-04,  2.56529810e+03, -5.08534395e-05,
        -4.36607212e-01,  4.42758746e-11],
       [-4.41249576e-05,  1.35274050e-14, -4.53312827e+12,
        -1.08870385e-10, -2.13584709e-22],
       [ 3.83202632e-06,  0.00000000e+00,  7.93258754e+12,
        -1.57852498e+10,  1.97842301e+18],
       [ 0.00000000e+00,  2.01241388e+25, -0.00000000e+00,
        -1.52075394e-32,  0.00000000e+00]], dtype=float32)>

### 5. Tampilkan nilai maksimum dan minimum dari variable random_tensor.

In [22]:
max_random_kolom_tensor = tf.argmax(random_tensor, axis = 0)
max_random_baris_tensor = tf.argmax(random_tensor, axis = 1)

print("Nilai Maksimum")
print("Berdasarkan Kolom", max_random_kolom_tensor)
print("Berdasarkan Baris", max_random_baris_tensor)

Nilai Maksimum
Berdasarkan Kolom tf.Tensor([0 4 3 0 3], shape=(5,), dtype=int64)
Berdasarkan Baris tf.Tensor([0 1 1 4 1], shape=(5,), dtype=int64)


In [23]:
min_random_kolom_tensor = tf.argmin(random_tensor, axis = 0)
min_random_baris_tensor = tf.argmin(random_tensor, axis = 1)

print("Nilai Minimum")
print("Berdasarkan Kolom", min_random_kolom_tensor)
print("Berdasarkan Baris", min_random_baris_tensor)

Nilai Minimum
Berdasarkan Kolom tf.Tensor([2 0 2 3 2], shape=(5,), dtype=int64)
Berdasarkan Baris tf.Tensor([1 3 2 3 3], shape=(5,), dtype=int64)


### 6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [16]:
concat_random_prime = tf.concat([random_tensor, prime_tensor], axis = 0)
concat_random_prime

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[ 8.0157036e-01, -7.6805395e-01,  4.7505453e-02,  6.0564154e-01,
         1.1260842e-01],
       [ 5.3367996e-01,  1.5868560e+00, -5.9431523e-01, -9.6461004e-01,
         4.3951255e-01],
       [-7.2361231e-01,  4.2185962e-01, -2.0356009e+00, -5.8654350e-01,
        -3.4588125e-01],
       [ 7.9031557e-01,  2.1720563e-01,  1.6272932e+00, -1.4197527e+00,
         1.8100669e+00],
       [ 9.8644614e-02,  2.0907409e+00, -5.2086018e-02, -4.3903086e-01,
         1.9157891e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

### 7. Tampilkan hasil sorting dari kedua variable di atas (descending)

#### Sorting Secara Descending Random_Tensor

In [19]:
random_tensor_desc = tf.sort(random_tensor, direction = "DESCENDING")
random_tensor_desc

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.80157036,  0.60564154,  0.11260842,  0.04750545, -0.76805395],
       [ 1.586856  ,  0.53367996,  0.43951255, -0.59431523, -0.96461004],
       [ 0.42185962, -0.34588125, -0.5865435 , -0.7236123 , -2.035601  ],
       [ 1.8100669 ,  1.6272932 ,  0.79031557,  0.21720563, -1.4197527 ],
       [ 2.090741  ,  0.19157891,  0.09864461, -0.05208602, -0.43903086]],
      dtype=float32)>

#### Sorting Secara Descending Prime_Tensor

In [20]:
prime_tensor_desc = tf.sort(prime_tensor, direction = "DESCENDING")
prime_tensor_desc

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)>